version: "3.8"

services:
  ygz.identity.postgres:
    image: postgres:18.4-alpine3.23
    container_name: ygz.identity.postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${IDENTITY_POSTGRES_DB_NAME}
      POSTGRES_USER: ${IDENTITY_POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${IDENTITY_POSTGRES_DB_PASSWORD}
    ports:
      - "${IDENTITY_POSTGRES_DB_PORT}:5432"
    volumes:
      - ygz-identity-postgres:/var/lib/postgresql
    networks:
      - ygz-app-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${IDENTITY_POSTGRES_DB_USER} -d ${IDENTITY_POSTGRES_DB_NAME}",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  ygz.redis:
    image: redis:8.0-alpine
    container_name: ygz.redis
    restart: unless-stopped
    environment:
      REDIS_DB: ${CACHE_REDIS_DB}
      REDIS_USER: ${CACHE_REDIS_USER}
      REDIS_PASSWORD: ${CACHE_REDIS_PASSWORD}
    ports:
      - "${CACHE_REDIS_PORT}:6379"
    volumes:
      - ygz-redis:/data
      - ./volumes/configs/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - ygz-app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  ygz.queue.rabbitmq:
    image: rabbitmq:4.1.3-management-alpine
    container_name: ygz.queue.rabbitmq
    restart: unless-stopped
    ports:
      - "${MESSAGE_QUEUE_RABBITMQ_PORT:-5672}:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${MESSAGE_QUEUE_RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${MESSAGE_QUEUE_RABBITMQ_PASSWORD:-guest}
    networks:
      - ygz-app-network
    volumes:
      - ygz-rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  ygz.grafana:
    image: grafana/grafana:11.0.0
    container_name: ygz.grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - ygz.logs.loki
    volumes:
      - ygz-grafana-data:/var/lib/grafana
    networks:
      - ygz-app-network

  ygz.logs.loki:
    image: grafana/loki:2.9.0
    container_name: ygz.logs.loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ygz-loki-data:/loki
    networks:
      - ygz-app-network

  ygz.logs.promtail:
    image: grafana/promtail:2.9.0
    container_name: ygz.logs.promtail
    restart: unless-stopped
    volumes:
      - ../logs:/var/log
      - ./volumes/configs/promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - ygz.logs.loki
    networks:
      - ygz-app-network

volumes:
  ygz-identity-postgres:
  ygz-redis:
  ygz-rabbitmq:
  ygz-grafana-data:
  ygz-loki-data:

networks:
  ygz-app-network:
    driver: bridge
