// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	UserID        int32              `json:"user_id"`
	UserUuid      uuid.UUID          `json:"user_uuid"`
	UserEmail     string             `json:"user_email"`
	UserPassword  string             `json:"user_password"`
	UserFullname  string             `json:"user_fullname"`
	UserAge       *int32             `json:"user_age"`
	UserStatus    int32              `json:"user_status"`
	UserLevel     int32              `json:"user_level"`
	UserDeletedAt pgtype.Timestamptz `json:"user_deleted_at"`
	UserCreatedAt time.Time          `json:"user_created_at"`
	UserUpdatedAt time.Time          `json:"user_updated_at"`
}
