// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUser(ctx context.Context, userUuid uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, userEmail string) (User, error)
}

var _ Querier = (*Queries)(nil)
