CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Create table
CREATE TABLE IF NOT EXISTS users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uuid UUID NOT NULL DEFAULT gen_random_uuid () UNIQUE,
    user_email VARCHAR(150) NOT NULL UNIQUE,
    user_password VARCHAR(90) NOT NULL,
    user_fullname VARCHAR(100) NOT NULL,
    user_age INT CHECK (
        user_age >= 1
        AND user_age <= 150
    ),
    user_status INT NOT NULL DEFAULT 1 CHECK (user_status IN (1, 2, 3)),
    user_level INT NOT NULL DEFAULT 1 CHECK (user_level IN (1, 2, 3)),
    user_deleted_at TIMESTAMPTZ DEFAULT NULL,
    user_created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);